spring.application.name=portfolio-api

# ===============================
# Profile
# ===============================
# 環境変数にSPRING_PROFILES_ACTIVEが設定されていない時はlocalファイルを参照(ローカル起動時のみ有効化される仕組み)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# ===============================
# Server
# ===============================

# RenderではPORT環境変数を使用
# ローカルではPORTがないので8080を使用
server.port=${PORT:8080}

# 外部からのHTTP接続を受け付ける
server.address=0.0.0.0

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# ===============================
# NeonPostgreSQL
# ===============================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
# SQLを表示有無
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
# SQLを見やすくする
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# CORS
# =========================

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}


# ===============================
# UTF-8
# ===============================

spring.messages.encoding=UTF-8


# =========================
# JWT設定
# =========================

# JWT署名に使用する秘密鍵
app.jwt.secret=${JWT_SECRET_BASE64}

# JWTを発行したアプリの識別子
app.jwt.issuer=${JWT_ISSUER:portfolio-api}

# アクセストークンの有効時間
# 単位は分
app.jwt.access-token-minutes=60