spring.application.name=portfolio-api

# ===============================
# Server Encoding
# ===============================

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5433/portfolio
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQLを見やすくする
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# UTF-8
# ===============================

spring.messages.encoding=UTF-8